const App={state:null,submitting:false,
 fresh(){return {student:null,studentId:null,warmupDone:false,learning:[],practice:[],final:{code:'',requirements:{}},part1SubmittedAt:null,finalSubmittedAt:null}},
 save(){Store.write(this.state)},
 completed(kind){const tasks=kind==='learning'?Learning.activities:Practice.activities;return tasks.every(t=>this.state[kind].find(r=>r.activityId===t.id)?.passed)},
 availableIndex(kind){const tasks=kind==='learning'?Learning.activities:Practice.activities;const first=tasks.findIndex(t=>!this.state[kind].find(r=>r.activityId===t.id)?.passed);return first<0?tasks.length-1:first},
 frontier(){if(!this.state.student)return 'home';if(!this.state.warmupDone)return 'warmup';if(!this.completed('learning'))return 'learning';if(!this.completed('practice'))return 'practice';return 'final'},
 canAccess(stage){return ['home','warmup','learning','practice','final'].indexOf(stage)<=['home','warmup','learning','practice','final'].indexOf(this.frontier())},
 verifyState(){let previous=true;for(const kind of ['learning','practice']){const tasks=kind==='learning'?Learning.activities:Practice.activities;for(const task of tasks){const r=this.state[kind].find(x=>x.activityId===task.id);if(r){r.passed=previous&&r.passed&&task.validate(r.studentCode||'').passed;previous=r.passed}else previous=false}}},
 invalidateAfter(kind,index){const tasks=kind==='learning'?Learning.activities:Practice.activities;tasks.slice(index+1).forEach(t=>{const r=this.state[kind].find(x=>x.activityId===t.id);if(r)r.passed=false});if(kind==='learning')this.state.practice.forEach(r=>r.passed=false);this.state.part1SubmittedAt=null;this.state.finalSubmittedAt=null;this.nav()},
 nav(){const stage=(location.hash.slice(1)||'home').split('/')[0];document.querySelector('#steps').innerHTML=[['home','Tổng quan'],['warmup','Khởi động'],['learning','Hình thành kiến thức'],['practice','Luyện tập'],['final','Vận dụng']].map(([s,label],i)=>`<a href="#${s}" class="${stage===s?'active':''} ${this.canAccess(s)?'':'locked'}" ${stage===s?'aria-current="step"':''}><span class="num">${this.canAccess(s)?String(i).padStart(2,'0'):'·'}</span>${label}</a>`).join('');document.querySelector('#student-badge').innerHTML=this.state.student?`<strong>${Util.esc(this.state.student.name)}</strong><br>${Util.esc(this.state.student.className)}<br><button id="switch-student" class="secondary">Đổi học sinh / nhóm</button>`:'';document.querySelector('#switch-student')?.addEventListener('click',()=>{if(confirm('Đổi học sinh sẽ bắt đầu lượt học mới trên máy này. Hãy tải bản sao nếu cần giữ bài chưa nộp. Tiếp tục?')){Util.download('bai-10-ban-sao.json',JSON.stringify(this.state,null,2),'application/json');this.state=this.fresh();this.save();location.hash='home';this.route()}})},
 route(){let [stage,index]=location.hash.slice(1).split('/');stage=stage||'home';if(!['home','warmup','learning','practice','final'].includes(stage)||!this.canAccess(stage)){const next=this.frontier();if(stage!==next)Util.toast('Em hãy làm xong bài hiện tại trước khi sang phần tiếp theo nhé.');location.hash=next;return}this.nav();if(stage==='home')this.home();if(stage==='warmup')this.warmup();if(stage==='learning'||stage==='practice'){if(index===undefined&&this.completed(stage)){this.renderStageDone(stage);return}const i=Math.max(0,Math.min(Number.parseInt(index,10)||0,this.availableIndex(stage)));(stage==='learning'?Learning:Practice).render(i)}if(stage==='final')Final.render()},
 home(){document.querySelector('#main').innerHTML=`<span class="tag">TIN HỌC 12 · BÀI 10</span><section class="hero"><div><h1>Nối các trang.<br><em>Làm website của lớp.</em></h1><p>Website là nhiều trang web được nối với nhau bằng liên kết. Trong bài này, em cùng lớp 12A xây một website nhỏ.</p><p>Em sẽ học cách viết liên kết, dùng đường dẫn cho đúng và làm trang giới thiệu bản thân của riêng mình.</p><a href="#home" onclick="document.querySelector('#join').scrollIntoView();return false" class="muted">Bắt đầu bên dưới ↓</a></div><div class="map-hero"><span class="eyebrow">WEBSITE CỦA LỚP 12A</span><pre>lop12a.edu.vn/
├── index.html       ← Trang chủ
├── gioi_thieu.html
├── thanh_vien/
│   ├── an.html
│   ├── binh.html
│   └── em.html      ← Trang của em
├── bai_tap/
│   └── tin_hoc.html
└── images/</pre><div class="route-line">&lt;a href="gioi_thieu.html"&gt;<br>&nbsp; Giới thiệu lớp<br>&lt;/a&gt;</div></div></section><div class="section-head"><h2>Bốn bước của bài học</h2><span class="muted">Học bằng cách tự viết mã</span></div><section class="journey"><article><span>BƯỚC 1</span><h3>Nhận biết liên kết</h3><p>Nhấp thử để biết cái gì trên trang web là liên kết.</p></article><article><span>BƯỚC 2</span><h3>Học viết liên kết</h3><p>6 loại liên kết, mỗi loại có mã mẫu, giải thích và khung thử ngay.</p></article><article><span>BƯỚC 3</span><h3>Luyện tập</h3><p>Làm menu, nối trang thành viên và sửa liên kết hỏng cho website lớp.</p></article><article><span>BƯỚC 4</span><h3>Trang của em</h3><p>Viết trang giới thiệu bản thân và nối vào website lớp.</p></article></section><section class="panel" id="join"><h3>${this.state.student?'Chào mừng em quay lại':'Sẵn sàng nhận nhiệm vụ?'}</h3>${this.state.student?`<p>${Util.esc(this.state.student.name)} · ${Util.esc(this.state.student.className)} — tiến độ và mã của em vẫn ở đây.</p><button id="continue">Tiếp tục học →</button>`:`<form id="join-form" class="join"><label>Họ tên học sinh / tên nhóm<input name="name" required maxlength="60" autocomplete="name" placeholder="Ví dụ: Nguyễn Minh An"></label><label>Lớp<input name="className" required maxlength="15" placeholder="Ví dụ: 12A"></label><button type="submit">Bắt đầu khám phá →</button></form><p class="connection">Bài làm của em được tự lưu trên máy này. Chỉ khi em bấm “Nộp bài”, họ tên, lớp và mã HTML của em mới được gửi cho giáo viên.</p>`}</section>`;document.querySelector('#continue')?.addEventListener('click',()=>location.hash=this.frontier());document.querySelector('#join-form')?.addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(e.target);const name=fd.get('name').trim(),className=fd.get('className').trim();const a=Util.id(className).slice(0,15),b=Util.id(name).slice(0,40);if(!a||!b){Util.toast('Em nhập tên và lớp có chữ hoặc số nhé.');return}this.state.student={name,className};this.state.studentId=a+'_'+b;this.save();Api.warmUp();location.hash='warmup'})},
 warmup(){document.querySelector('#main').innerHTML=`<div class="eyebrow">KHỞI ĐỘNG</div><h1>Đâu là liên kết?</h1><p class="lead">Đây là một bài viết trên website. Không phải chữ hay ảnh nào cũng là liên kết. Em hãy nhấp thử từng chi tiết trong bài: cái nào bấm được, cái nào không?</p><article class="mock-page"><div class="mock-bar"><i></i><i></i><i></i><span>tinhoc12.edu.vn/bai-viet/hoc-tin-hieu-qua</span></div><div class="mock-body"><div class="mock-text"><span class="tag">GÓC HỌC TẬP</span><h2>5 mẹo học Tin học hiệu quả hơn</h2><p class="byline">Đăng bởi <button class="linklike mention" data-door="profile">@co_giao_tin</button> · 08/10/2026 · <b>4 phút đọc</b></p><p>Muốn làm được website đầu tay, em nên bắt đầu từ <b>HTML</b> và luyện gõ mã mỗi ngày. Nếu chưa biết bắt đầu từ đâu, hãy đọc bài <button class="linklike" data-door="book">Cách tạo trang web đầu tiên của em</button> trước khi làm bài tập.</p><p class="muted">Lưu ý: Bài viết cập nhật lần cuối ngày 05/10/2026.</p></div><button class="thumb" data-door="map" aria-label="Xem bản đồ dự án"><img src="assets/images/project.svg" width="72" height="72" alt="Ảnh bìa bài viết"><span>Sơ đồ thư mục của một website</span></button></div></article><div id="door-result" class="panel" role="status"><h3>Em đã tìm thấy <span id="door-count">0</span>/3 liên kết</h3><p>Hãy nhấp vào cả 3 chi tiết bấm được: tên tác giả, cụm chữ màu xanh và ảnh bìa.</p></div><div class="panel"><h3>Suy nghĩ và trao đổi</h3><p>Chỗ bấm được có thể là chữ, tên tài khoản hoặc hình ảnh. Tất cả đều đưa em đến một trang khác hoặc một vị trí khác. Đó gọi là <strong>liên kết</strong>.</p><p class="muted">Đọc sách, em đọc lần lượt từ đầu đến cuối. Trên web, em được chọn nhiều lối đi. Vậy trình duyệt biết phải đi đâu bằng cách nào? Em sẽ tìm hiểu bằng HTML ở bước sau.</p><button id="finish-warmup" ${this.state.warmupDone?'':'disabled'}>Học cách viết liên kết →</button></div>`;const found=new Set();document.querySelectorAll('[data-door]').forEach(b=>b.onclick=()=>{found.add(b.dataset.door);const messages={book:'Em vừa nhấp vào một cụm chữ xanh gạch chân: liên kết có thể là văn bản trong đoạn.',profile:'Em vừa nhấp vào tên tài khoản: một tên hay nhãn cũng có thể dẫn đến trang khác.',map:'Em vừa nhấp vào ảnh bìa: hình ảnh cũng có thể là một liên kết.'};document.querySelector('#door-result').innerHTML=`<h3>Đã tìm thấy ${found.size}/3 liên kết</h3><p>${messages[b.dataset.door]}</p>`;if(found.size===3)document.querySelector('#finish-warmup').disabled=false});document.querySelector('#finish-warmup').onclick=()=>{this.state.warmupDone=true;this.save();location.hash='learning/0'}},
 renderStageDone(kind){this.nav();document.querySelector('#main').innerHTML=kind==='learning'?`<div class="eyebrow">HOÀN THÀNH HÌNH THÀNH KIẾN THỨC</div><h1>Em đã biết viết các loại liên kết.</h1><p class="lead">Em đã học xong 6 loại liên kết: URL tuyệt đối, cùng thư mục, thư mục con, thư mục cha (../), liên kết neo và liên kết ảnh.</p><div class="panel"><h2>Sẵn sàng luyện tập?</h2><p>Ở phần luyện tập, em dùng các loại liên kết này để hoàn thiện website của lớp. Cần nhớ cú pháp thì bấm nút “Từ điển HTML” ở góc trên.</p><button id="next-stage">Vào luyện tập →</button></div>`:`<div class="eyebrow">LUYỆN TẬP · HOÀN THÀNH</div><h1>Website của lớp đã hoạt động!</h1><div class="panel"><span class="tag">HOÀN THÀNH PHẦN 1</span><p>Em đã làm menu trang chủ, nối trang thành viên và sửa các liên kết hỏng. Các trang của lớp giờ đã nối được với nhau.</p><button id="submit-part1">Nộp phần 1 cho giáo viên →</button><div id="submit-status" role="status"></div></div><button id="next-stage" class="secondary">Tiếp tục vận dụng →</button><p class="muted">Nếu mạng bị lỗi, bài vẫn được lưu trên máy. Khi nộp bài vận dụng, phần 1 sẽ được gửi bù.</p>`;const reviewTasks=kind==='learning'?Learning.activities:Practice.activities;document.querySelector('#main').insertAdjacentHTML('beforeend',`<div class="panel"><h3>Xem lại bài đã làm</h3><p class="muted">Em bấm vào từng bài để xem lại mã mẫu, phần giải thích và bài làm của mình.</p><div class="review-list">${reviewTasks.map((t,i)=>`<a class="review-link" href="#${kind}/${i}"><b>${i+1}</b> ${Util.esc(t.name)}</a>`).join('')}</div></div>`);document.querySelector('#next-stage').onclick=()=>location.hash=kind==='learning'?'practice/0':'final';document.querySelector('#submit-part1')?.addEventListener('click',()=>Practice.submitPart1())},
 async submit(type){if(this.submitting)return;const status=document.querySelector('#submit-status');const say=t=>{if(status)status.textContent=t};if(!this.completed('learning')||!this.completed('practice')){say('Em cần hoàn thành phần kiến thức và luyện tập trước khi nộp.');return}if(type==='final'&&!Validators.final(this.state.final.code||'').passed){say('Bài vận dụng còn thiếu yêu cầu.');return}this.submitting=true;say('Đang gửi bài, em chờ xác nhận từ máy chủ…');try{if(type==='final'&&!this.state.part1SubmittedAt){await Api.send({type:'part1'});this.state.part1SubmittedAt=new Date().toISOString();this.save()}await Api.send({type});this.state[type==='part1'?'part1SubmittedAt':'finalSubmittedAt']=new Date().toISOString();this.save();say('Đã gửi '+(type==='part1'?'phần 1':'bài vận dụng')+' thành công. Giáo viên có thể xem bài của em.');Util.toast('Đã nộp '+(type==='part1'?'phần 1':'bài vận dụng')+' thành công ✓');setTimeout(()=>this.submitting=false,5000)}catch(e){this.submitting=false;say('Không thể gửi bài. Bài vẫn được lưu trên máy. '+(e.code==='permission-denied'?'Giáo viên cần kiểm tra Firestore Rules.':e.message||'Em kiểm tra kết nối rồi thử lại.'))}},
 init(){const saved=Store.read();this.state=saved&&Array.isArray(saved.learning)&&Array.isArray(saved.practice)?{...this.fresh(),...saved}:this.fresh();this.verifyState();window.addEventListener('hashchange',()=>this.route());Dictionary.init();this.route()}
};
const Dictionary={entries:[
 ['<a>','Thẻ tạo liên kết. Chữ (hoặc ảnh) đặt giữa thẻ mở và thẻ đóng là phần em bấm vào.','<a href="dia-chi">Nội dung liên kết</a>'],
 ['href','Thuộc tính của thẻ a, cho biết liên kết sẽ đi đến đâu.','<a href="https://www.wikipedia.org/">Wikipedia</a>'],
 ['Đường dẫn tuyệt đối','Địa chỉ đầy đủ, bắt đầu bằng https:// và có tên website. Viết ở thư mục nào cũng không đổi.','https://example.com/tai-lieu/bai-10.html'],
 ['Đường dẫn tương đối','Đường đi tính từ thư mục chứa tệp em đang viết. Cùng thư mục chỉ cần tên tệp; vào thư mục con thì viết tên thư mục và dấu /. ./ nghĩa là thư mục hiện tại.','gioi_thieu.html\nthanh_vien/an.html\n./gioi_thieu.html'],
 ['../ · Thư mục cha','Mỗi ../ đi lên một thư mục. ../../ đi lên hai thư mục.','<a href="../index.html">Về trang chủ</a>'],
 ['/ · Gốc website','Dấu / ở đầu nghĩa là bắt đầu từ gốc của cả website, không phải đi lên một thư mục.','/images/anh.jpg'],
 ['id và # · Liên kết neo','id đánh dấu nơi muốn đến; href="#tên-id" nhảy đến đó. Mỗi id chỉ dùng một lần trong trang.','<a href="#ky-nang">Kỹ năng</a>\n<h2 id="ky-nang">Kỹ năng của em</h2>'],
 ['<img>, src, alt · Liên kết ảnh','img hiện ảnh. src là nơi lấy ảnh; alt là mô tả ảnh. Đặt img trong a thì bấm vào ảnh sẽ mở liên kết.','<a href="san-pham.html">\n  <img src="images/anh.jpg" alt="Xem sản phẩm">\n</a>'],
 ['target="_blank"','Mở liên kết trong một tab mới của trình duyệt. Nên viết kèm rel="noopener" cho an toàn.','<a href="https://example.com" target="_blank" rel="noopener">Mở trang</a>'],
 ['<h1>, <h2>, <p>','h1: tiêu đề chính; h2: tiêu đề từng mục; p: đoạn văn. Dùng để chia CV thành các phần và gắn id cho liên kết neo.','<h1>CV của em</h1>\n<h2 id="du-an">Dự án</h2>\n<p>Giới thiệu dự án của em.</p>']
 ],init(){const dialog=document.querySelector('#dictionary');document.querySelector('#dictionary-button').onclick=()=>{dialog.showModal();this.render('');document.querySelector('#dictionary-search').value='';document.querySelector('#dictionary-search').focus()};document.querySelector('#close-dictionary').onclick=()=>dialog.close();document.querySelector('#dictionary-search').oninput=e=>this.render(e.target.value)},render(query){const normalized=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();const rows=this.entries.filter(e=>normalized(e.join(' ')).includes(normalized(query)));document.querySelector('#dictionary-results').innerHTML=rows.length?rows.map(([name,text,code])=>`<article class="dict-entry"><strong>${Util.esc(name)}</strong><p>${Util.esc(text)}</p><pre>${Util.esc(code)}</pre></article>`).join(''):'<p>Chưa tìm thấy. Em thử “href”, “neo”, “ảnh” hoặc “../”.</p>'}};
App.init();
