/* Giai đoạn Vận dụng: học sinh tự viết trang giới thiệu bản thân (thanh_vien/em.html) trong website của lớp. */
const Final={FILE:Validators.FINAL_FILE,urls:[{label:'GitHub',url:'https://github.com/'},{label:'MDN Web Docs',url:'https://developer.mozilla.org/'},{label:'Wikipedia',url:'https://www.wikipedia.org/'},{label:'W3Schools',url:'https://www.w3schools.com/'},{label:'Khan Academy',url:'https://www.khanacademy.org/'}],
render(){
 const record=App.state.final,FILE=this.FILE;
 document.querySelector('#main').innerHTML=`<div class="eyebrow">VẬN DỤNG · TRANG CỦA EM</div><h1>Trang giới thiệu bản thân.</h1><p class="lead">Em đã nối xong các trang của lớp. Bây giờ hãy làm trang riêng của em và nối nó vào website lớp 12A.</p>
<div class="panel"><h3>Đề bài · Viết tệp ${FILE}</h3><p>Viết trang giới thiệu về em (sở thích, kỹ năng, dự định). Tệp nằm trong thư mục <code>thanh_vien</code>, cùng thư mục với trang của An và Bình. Trang cần có đủ 5 phần sau:</p><ol class="task-steps"><li>Một tiêu đề <code>&lt;h1&gt;</code> và một đoạn giới thiệu <code>&lt;p&gt;</code> dài ít nhất 30 ký tự.</li><li><strong>3 liên kết ra website ngoài</strong>, mỗi liên kết một URL khác nhau (bấm nút “URL gợi ý” để chèn).</li><li>1 liên kết neo nhảy đến một mục trong trang, ví dụ mục “Sở thích”.</li><li>1 liên kết “Về trang chủ” mở <code>index.html</code>.</li><li>Ảnh <code>../images/em.jpg</code> là liên kết mở trang Giới thiệu lớp <code>gioi_thieu.html</code>, có alt.</li></ol><p class="muted">Em làm xong phần nào, bảng “Checklist” bên dưới tự đánh dấu ✓. Khi đủ 5 mục, em bấm “Nộp bài vận dụng”. Em có thể hoàn thiện ở nhà, bài tự lưu trên máy.</p></div>${Activity.treeBox(FILE)}${Activity.urlBar(Final.urls)}
<div class="workspace"><section class="editor-side"><div class="pane-head"><span>${FILE}</span><span>TRANG CỦA EM</span></div><div class="code-wrap"><div class="lines">1</div><textarea id="code" aria-label="Mã trang giới thiệu" maxlength="100000" spellcheck="false" placeholder="Tự viết trang của em bằng những thẻ đã học…">${Util.esc(record.code||'')}</textarea></div></section><section class="preview-side"><div class="pane-head"><span>KẾT QUẢ TRỰC TIẾP</span><span>Bấm thử liên kết</span></div><iframe id="preview" sandbox="allow-scripts allow-popups allow-popups-to-escape-sandbox" title="Trang của em"></iframe><div id="preview-links" class="preview-links"></div></section></div>
<div class="panel"><h3>Checklist sản phẩm</h3><div id="final-checks"></div><div class="actions"><button id="submit-final" aria-disabled="true">Nộp bài vận dụng →</button><button id="download-final" class="secondary">Tải tệp HTML</button><button id="backup" class="secondary">Tải bản sao toàn bộ bài</button></div><div id="submit-status" role="status"></div></div>`;
 const textarea=document.querySelector('#code');
 const update=()=>{record.code=textarea.value;const r=Validators.final(record.code);record.requirements=Object.fromEntries(r.checks.map(c=>[c.id,c.ok]));document.querySelector('#final-checks').innerHTML=Activity.checklist(r.checks);document.querySelector('#submit-final').setAttribute('aria-disabled',String(!r.passed));Preview.update(document.querySelector('#preview'),record.code,FILE);Preview.links(document.querySelector('#preview-links'),record.code,FILE);App.save();Store.saveCode('final',record.code)};
 Editor.mount(textarea,record,update,false);Activity.bindUrls(textarea,record);update();
 document.querySelector('#submit-final').onclick=()=>{const r=Validators.final(record.code);if(!r.passed){document.querySelector('#submit-status').textContent='Còn thiếu: '+r.checks.filter(c=>!c.ok).map(c=>c.label).join('; ');return}App.submit('final')};
 document.querySelector('#download-final').onclick=()=>Util.download('em.html',record.code);
 document.querySelector('#backup').onclick=()=>Util.download('bai-10-ban-sao.json',JSON.stringify(App.state,null,2),'application/json');
}};
