/* Giai đoạn Hình thành kiến thức. Dự án xuyên suốt: xây website cho lớp 12A.
   Mỗi bài: lời dẫn ngắn (intro) → mã mẫu tô màu có chú thích từng thành phần (parts)
   → khung kết quả cho thấy tác dụng của thẻ (previewHtml, effect) → nhiệm vụ viết thêm vào mã có sẵn (starter).
   parts = [đoạn mã, chú thích (để trống nếu không cần), số màu 1-5]
   showTree: hiện sơ đồ thư mục của website để học sinh biết mình đang đứng ở đâu. */
const FILLER='Em đọc kỹ lý thuyết, làm lại các ví dụ trong sách và ghi chú những phần còn chưa hiểu. Sau đó làm bài tập từ dễ đến khó, đối chiếu đáp án và sửa lỗi sai.';
const LONG_PARAGRAPHS=Array.from({length:5},(_,i)=>`<p>Phần ${i+1}. ${FILLER}</p>`).join('\n');
const Learning={activities:[
 {id:'learn-absolute',name:'Liên kết ra ngoài',title:'Thẻ <a> biến chữ thành liên kết',current:'index.html',
  intro:'Thẻ <a> biến một đoạn chữ thành liên kết. URL tuyệt đối là địa chỉ đầy đủ của một website, luôn bắt đầu bằng https://. Dùng nó khi muốn dẫn người xem sang một website khác.',
  parts:[['<a ','Thẻ a: biến phần chữ bên trong thành liên kết',1],['href="https://www.wikipedia.org/"','href: địa chỉ nơi liên kết dẫn tới (URL tuyệt đối)',2],['>','',1],['Khám phá Wikipedia','Chữ hiện trên trang, là phần em bấm vào',3],['</a>','Đóng thẻ a: hết liên kết',1]],
  previewHtml:'<p><b>Chữ thường</b> (bấm không có gì): Khám phá Wikipedia</p>\n<p><b>Chữ trong thẻ a</b> (bấm được): <a href="https://www.wikipedia.org/">Khám phá Wikipedia</a></p>',
  effect:'Hai dòng có cùng chữ, nhưng chỉ dòng nằm trong thẻ <a> bấm được: bấm vào sẽ mở website ghi trong href ở tab mới.',
  starter:'<h1>Góc học tập của lớp 12A</h1>\n<p>Muốn học thêm kiến thức mới, các em hãy ghé thăm một website học tập.</p>\n<!-- Viết liên kết dẫn tới một website học tập ngay dưới dòng này, giống mẫu ở trên -->\n',
  task:['Mã bên trái đã có sẵn tiêu đề và một câu giới thiệu.','Viết thêm một liên kết có chữ “Tìm hiểu thêm”, giống mẫu ở trên.','href là một URL tuyệt đối. URL dài thì bấm nút “URL gợi ý” để chèn.'],
  urls:[{label:'Wikipedia',url:'https://www.wikipedia.org/'},{label:'MDN Web Docs',url:'https://developer.mozilla.org/'},{label:'Khan Academy',url:'https://www.khanacademy.org/'}],
  validate:html=>Validators.link(html,{kind:'absolute'})},
 {id:'learn-same',name:'Cùng thư mục',title:'Liên kết giữa hai trang cùng thư mục',current:'index.html',showTree:true,
  intro:'Website của lớp gồm nhiều trang. Hai trang nằm cùng thư mục thì chỉ cần viết tên tệp trong href, không cần https://. Đây là đường dẫn tương đối: đường đi tính từ trang em đang viết.',
  parts:[['<a ','Thẻ a: tạo liên kết',1],['href="gioi_thieu.html"','href: tên tệp cần mở. index.html và gioi_thieu.html nằm cùng thư mục nên chỉ cần viết tên tệp',2],['>','',1],['Giới thiệu lớp','Chữ em bấm vào',3],['</a>','Đóng thẻ a',1]],
  previewHtml:'<h2>Website lớp 12A</h2>\n<p>Chào mừng các bạn!</p>\n<p><a href="gioi_thieu.html">Giới thiệu lớp</a></p>',
  effect:'Bấm “Giới thiệu lớp”: trình duyệt mở tệp gioi_thieu.html nằm cùng thư mục với trang hiện tại. Hộp “Trang đích” cho em thấy trang được mở.',
  starter:'<h1>Website lớp 12A</h1>\n<p>Chào mừng các bạn đến với website của lớp.</p>\n<!-- Viết liên kết “Giới thiệu lớp” mở tệp gioi_thieu.html, giống mẫu ở trên -->\n',
  task:['Em đang ở index.html (trang chủ).','Viết thêm liên kết có chữ “Giới thiệu lớp”.','Liên kết mở tệp gioi_thieu.html, nằm cùng thư mục với index.html.','Hai tệp cùng thư mục thì chỉ cần viết tên tệp.'],
  validate:html=>Validators.link(html,{kind:'relative',target:'gioi_thieu.html',current:'index.html'})},
 {id:'learn-child',name:'Vào thư mục con',title:'Liên kết đến tệp trong thư mục con',current:'index.html',showTree:true,
  intro:'Khi tệp đích nằm trong một thư mục con, em viết tên thư mục, dấu /, rồi tên tệp. Ví dụ trang của bạn An nằm trong thư mục thanh_vien.',
  parts:[['<a ','Thẻ a: tạo liên kết',1],['href="thanh_vien/an.html"','href: thanh_vien/ là đi vào thư mục thanh_vien, an.html là tệp cần mở',2],['>','',1],['Trang của An','Chữ em bấm vào',3],['</a>','Đóng thẻ a',1]],
  previewHtml:'<h2>Website lớp 12A</h2>\n<p>Thành viên của lớp:</p>\n<p><a href="thanh_vien/an.html">Trang của An</a></p>',
  effect:'Bấm “Trang của An”: trình duyệt đi từ index.html vào thư mục thanh_vien và mở tệp an.html. Hộp “Trang đích” cho em thấy trang được mở.',
  starter:'<h1>Website lớp 12A</h1>\n<p>Thành viên của lớp:</p>\n<!-- Viết liên kết “Trang của An” mở tệp an.html trong thư mục thanh_vien, giống mẫu ở trên -->\n',
  task:['Em đang ở index.html.','Viết thêm liên kết có chữ “Trang của An”.','Liên kết mở tệp an.html nằm trong thư mục thanh_vien.','Chú ý viết đúng chữ hoa, chữ thường.'],
  validate:html=>Validators.link(html,{kind:'relative',target:'thanh_vien/an.html',current:'index.html'})},
 {id:'learn-parent',name:'Lên thư mục cha',title:'Dùng ../ để đi lên thư mục cha',current:'thanh_vien/an.html',showTree:true,
  intro:'Bây giờ em đang ở trang của An, nằm trong thư mục thanh_vien. Muốn quay về trang chủ index.html ở thư mục bên ngoài, em dùng ../ để đi lên một thư mục (gọi là thư mục cha).',
  parts:[['<a ','Thẻ a: tạo liên kết',1],['href="../index.html"','href: ../ là đi lên một thư mục (ra khỏi thanh_vien), index.html là tệp cần mở',2],['>','',1],['Về trang chủ','Chữ em bấm vào',3],['</a>','Đóng thẻ a',1]],
  previewHtml:'<h2>Trang của An</h2>\n<p>An là lớp trưởng của lớp 12A.</p>\n<p><a href="../index.html">Về trang chủ</a></p>',
  effect:'Bấm “Về trang chủ”: trình duyệt đi lên một thư mục (ra khỏi thanh_vien) rồi mở index.html. Nếu thiếu ../ thì trình duyệt tìm index.html ngay trong thanh_vien và báo 404.',
  starter:'<h1>Trang của An</h1>\n<p>An là lớp trưởng của lớp 12A.</p>\n<!-- Viết liên kết “Về trang chủ” mở index.html, giống mẫu ở trên -->\n',
  task:['Em đang ở thanh_vien/an.html.','Viết thêm liên kết có chữ “Về trang chủ”.','Liên kết mở tệp index.html bằng đường dẫn tương đối.','Tệp index.html nằm ngoài thư mục thanh_vien, nên cần ../'],
  validate:html=>Validators.link(html,{kind:'relative',target:'index.html',current:'thanh_vien/an.html'})},
 {id:'learn-anchor',name:'Liên kết neo',title:'Liên kết neo: cuộn tới một vị trí trong trang',current:'bai_tap/tin_hoc.html',
  intro:'Liên kết neo giúp cuộn tới một vị trí trong cùng trang. Cần hai phần: liên kết có href="#tên" và đoạn đích có id="tên".',
  parts:[['<a ','Thẻ a: tạo liên kết',1],['href="#cuoi_trang"','href: dấu # rồi tên id. Nghĩa là “cuộn tới chỗ có id cuoi_trang”',2],['>','',1],['Xuống cuối trang','Chữ em bấm vào',3],['</a>','Đóng thẻ a',1],['\n'],['<p>…các đoạn văn dài (rút gọn)…</p>'],['\n'],['<p ','Thẻ p: đoạn văn ở cuối trang, là nơi sẽ cuộn tới',4],['id="cuoi_trang"','id: tên đánh dấu cho đoạn này. Viết giống tên trong href nhưng không có dấu #',5],['>','',4],['Em đã đến cuối trang!','Nội dung nơi đến',4],['</p>','',4]],
  previewHtml:'<h2>Đề cương ôn tập</h2>\n<p><a href="#cuoi_trang">Xuống cuối trang</a></p>\n'+LONG_PARAGRAPHS+'\n<p id="cuoi_trang">Em đã đến cuối trang!</p>',
  previewHeight:220,
  effect:'Trang rất dài, nhưng khi bấm “Xuống cuối trang”, trang tự cuộn thẳng tới đoạn có id="cuoi_trang" và tô vàng đoạn đó. Không có liên kết neo thì em phải tự kéo chuột xuống.',
  starter:'<h1>Đề cương ôn tập Tin học 12</h1>\n<!-- Thêm liên kết “Xuống cuối trang” ở đây, giống mẫu ở trên -->\n'+LONG_PARAGRAPHS+'\n<p>Hết đề cương. Chúc em ôn tập tốt!</p>\n',
  task:['Em có sẵn một đề cương rất dài.','Thêm liên kết có chữ “Xuống cuối trang” và href="#cuoi_trang".','Thêm id="cuoi_trang" vào đoạn văn cuối cùng.','Xem kết quả bên phải rồi bấm thử liên kết.'],
  validate:html=>Validators.link(html,{kind:'anchor',target:'cuoi_trang'})},
 {id:'learn-image',name:'Liên kết ảnh',title:'Đặt ảnh vào trong thẻ <a> để ảnh bấm được',current:'index.html',showTree:true,
  intro:'Muốn bấm vào một bức ảnh để đi đến trang khác, em đặt thẻ <img> vào bên trong thẻ <a>. href là trang sẽ mở ra, còn src là nơi lấy ảnh.',
  parts:[['<a ','Thẻ a: tạo liên kết',1],['href="gioi_thieu.html"','href: bấm vào ảnh thì đi đến đâu',2],['>','',1],['\n  '],['<img ','Thẻ img: hiện một bức ảnh (đặt bên trong thẻ a)',3],['src="images/logo.jpg"','src: lấy ảnh ở đâu',4],[' '],['alt="Logo lớp 12A"','alt: mô tả ảnh bằng chữ (hiện khi ảnh lỗi, và giúp máy đọc màn hình)',5],['>','',3],['\n'],['</a>','Đóng thẻ a',1]],
  previewHtml:'<p><b>Ảnh thường</b> (bấm không có gì):</p>\n<img src="images/logo.jpg" alt="Logo lớp 12A">\n<p><b>Ảnh trong thẻ a</b> (bấm được):</p>\n<a href="gioi_thieu.html"><img src="images/logo.jpg" alt="Logo lớp 12A"></a>',
  previewHeight:240,
  effect:'Hai bức ảnh giống nhau, nhưng chỉ ảnh nằm trong thẻ <a> bấm được: bấm vào sẽ mở trang Giới thiệu lớp. Nếu ảnh bị lỗi, chữ trong alt sẽ hiện thay ảnh.',
  starter:'<h1>Website lớp 12A</h1>\n<p>Logo của lớp dưới đây chưa bấm được.</p>\n<!-- Đặt ảnh vào trong một liên kết mở gioi_thieu.html, giống mẫu ở trên -->\n<img src="images/logo.jpg" alt="Logo lớp 12A">\n',
  task:['Em đang ở index.html, ảnh logo đã có sẵn.','Bọc ảnh trong thẻ <a> có href mở gioi_thieu.html.','Giữ nguyên alt mô tả ảnh.'],
  validate:html=>Validators.link(html,{kind:'relative',target:'gioi_thieu.html',current:'index.html',image:'images/logo.jpg'})}
],render(index=0){Activity.render('learning',this.activities,index)}};
Learning.activities.forEach(a=>{a.sample=a.parts.map(p=>p[0]).join('')});
